spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://118.24.153.209:3306/fx
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
  path: logs
  file: fx.log

server:
  port: ${random.int[7000,9999]}

#start: 70
#key: f0c35c13b2fffac65e411939bc2de921
#count: 500